
# C++ project
language: cpp

# Use Ubuntu 16.04 (Xenial)
dist: xenial

# Only build master and tags
if: branch = master OR tag IS present

git:
    submodules: true

env:
  global:
    - BINTRAY_USER=manromen
    # BINTRAY_KEY
    - secure: "lec4hnbgyt3+uEMe9RsoFoNmt71zY0PGE0a6ZUd0dOcBzCqqfC2wdB6+Y0/QIGKBKE78l9Z/B3v/kWeQBqjajLbh/TmIlLf7l1jVMG5eC5yONSmGTlidhlLBRIVIaOzopVFafexumj77CjHp9HQIntbBDwgQI2B1FThfyP5K5pvZ6is3BWsfrbXq4I1JCb3RqR6VG0/C5guNyASVy8aqKIFB0H662BGAcZcyWry4q5CsCdjxrJXfwNpSw0kjoHTLLUGz2o0jQGLnl/dwmFZX8sKaZqUrLLLyzbKp+98wBmTaCEgFSG7XVJFGbs/UCBRySPGNGoLhLm84a2jajNfIYHdb9YCtsewfeITcc/Byare303Q+Ht+cgpmqTpssXOngE8y5mHP5REEi/DRQMdkzq9RX4G/NGTjAkO1NDJWVwJ45ce6Hm8gvwT/wHIHqDxzYUPrDcZf6H2a9vIjLMLuLQl4gXI1HdZk7mWgrZjJbUPK1/u0ZxQWuEeAvScoPO53VLcld1Omb7dhTKWSy8EyTbGAJSveCrCLVNUc1zGMstQ8/mmQazlG7FYaUvzxDXIqe2SEMdv5o6LZ0Sa/pac7ubf9hezxbej234y7g+3qFR7splrIf+9Z1t9uiYoqVvHfZGLo5QgLYWP9m6JsVAXdFNrqIU7FfAYjZ4zajHusz5bE="
    - CONAN_REPOSITORY=https://api.bintray.com/conan/manromen/rgpaul
    - CONAN_REPOSITORY_NAME=rgpaul
    - CONAN_USER=rgpaul
    - CONAN_CHANNEL=stable
    - LIBRARY_VERSION=1.2.11

### before installing deps
before_install:
  # Download Android NDK from Google
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TARGET_PLATFORM" == "android" ]]; then
      curl -sSOL "https://dl.google.com/android/repository/android-ndk-${TRAVIS_ANDROID_NDK_VERSION}-linux-x86_64.zip";
      unzip -q -o android-ndk-${TRAVIS_ANDROID_NDK_VERSION}-linux-x86_64.zip;
    fi

### install deps
install:

  # Install conan (windows)
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install python3;
      choco install conan;
    fi

  # Install conan (linux / macos)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] || [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip3 install conan;
    fi

  # Add conan repository and apply conan config
  - conan remote add ${CONAN_REPOSITORY_NAME} ${CONAN_REPOSITORY}
  - conan config install ${TRAVIS_BUILD_DIR}/.travis/conan/config.zip

  # login to conan
  - conan user -p "$BINTRAY_KEY" -r ${CONAN_REPOSITORY_NAME} ${BINTRAY_USER}

### build script
script:
  # show OS/compiler version
  - uname -a

  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # macOS Builds
  - if [ "$TARGET_PLATFORM" == "macos" ]; then
      export MACOS_SDK_VERSION=$(xcodebuild -showsdks | grep macosx | awk '{print $4}' | sed 's/[^0-9,\.]*//g');
      echo "macOS SDK ${MACOS_SDK_VERSION}";
      conan create . zlib/${LIBRARY_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} -s os=Macos -s os.version=${MACOS_SDK_VERSION} -s arch=${TARGET_ARCH} -s build_type=${TARGET_BUILD_TYPE} -o shared=False;
    fi

  # iOS Builds
  - if [ "$TARGET_PLATFORM" == "ios" ]; then
      export IOS_SDK_VERSION=$(xcodebuild -showsdks | grep iphoneos | awk '{print $4}' | sed 's/[^0-9,\.]*//g');
      echo "iOS SDK ${IOS_SDK_VERSION}";
      
      conan create . zlib/${LIBRARY_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} -s os=iOS -s os.version=${IOS_SDK_VERSION} -s arch=${TARGET_ARCH} -s build_type=${TARGET_BUILD_TYPE} -o shared=False;
    fi

  # Windows Builds
  - if [ "$TARGET_PLATFORM" == "windows" ]; then
      conan create . zlib/${LIBRARY_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} -s os=Windows -s compiler="Visual Studio" -s compiler.runtime=MT -s arch=${TARGET_ARCH} -s build_type=${TARGET_BUILD_TYPE} -o shared=False;
    fi

deploy:
  provider: script
  script: bash .travis/conan-deploy.sh
  on:
    tags: true
    all_branches: true

### build matrix
matrix:
  include:
      
    # iOS - Release
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - TARGET_PLATFORM=ios
        - TARGET_ARCH=armv8
        - TARGET_BUILD_TYPE=Release

    # iOS - Debug
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - TARGET_PLATFORM=ios
        - TARGET_ARCH=armv8
        - TARGET_BUILD_TYPE=Debug

    # iOS - Simulator
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - TARGET_PLATFORM=ios
        - TARGET_ARCH=x86_64
        - TARGET_BUILD_TYPE=Debug

    # macOS - Release
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - TARGET_PLATFORM=macos
        - TARGET_ARCH=x86_64
        - TARGET_BUILD_TYPE=Release

    # macOS - Debug
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - TARGET_PLATFORM=macos
        - TARGET_ARCH=x86_64
        - TARGET_BUILD_TYPE=Debug

    # Windows - Debug
    # - os: windows
      
      # TODO: remove filter_secrets - for now we have to disable it due to the following issue:
      # https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/10
      # filter_secrets: false
      # env: 
        ## - TRAVIS_OS_NAME=windows
        ## - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        # - PATH=c:\python37:c:\python37\Scripts:$PATH
        # - TARGET_PLATFORM=windows
        # - TARGET_ARCH=x86_64
        # - TARGET_BUILD_TYPE=Debug
