version: '{build}'

image: Visual Studio 2017

# branches to build
branches:
  # whitelist
  only:
    - master

# Do build on tags (GitHub and BitBucket)
skip_tags: false

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      FLAGS: ""
      ARTIFACT_NAME: win10-msvc14.1-mt-s

init:
  - cmake --version
  - msbuild /version

install:
  # get submodules
  - git submodule update --init --recursive

  # store library version (via git tag) into environmental variable
  # - ps: $env:LIBRARY_VERSION = & git describe --abbrev=0 --tags

  # set protocol to tls version 1.2
  - ps: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
  
  - ps: python -m pip install --upgrade pip
  - ps: pip install conan

build_script:
  # Visual Studio Compiler Versions:
  # Visual Studio 12 2013
  # Visual Studio 14 2015
  # Visual Studio 15 2017

  - ps: conan create . zlib/1.2.11@rgpaul/stable -s os=Windows -s compiler="Visual Studio" -s compiler.version=15 -s compiler.runtime=MT -s arch=${arch} -s build_type=Release -o shared=False
