name: Android

env:
  BINTRAY_USER: manromen
  CONAN_REPOSITORY: https://api.bintray.com/conan/manromen/rgpaul
  CONAN_REPOSITORY_NAME: rgpaul
  CONAN_PACKAGE_NAME: zlib
  CONAN_USER: rgpaul
  CONAN_CHANNEL: stable

on: 
  push:
    branches:
      - master

jobs:

  armv7-Release:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh armv7 19 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  armv7-Debug:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh armv7 19 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  armv8-Release:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh armv8 21 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  armv8-Debug:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh armv8 21 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  x86-Release:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh x86 19 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  x86-Debug:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh x86 19 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  x86_64-Release:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh x86_64 21 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  x86_64-Debug:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OS_NAME: linux
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-android.sh x86_64 21 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
