name: iOS

env:
  BINTRAY_USER: manromen
  CONAN_REPOSITORY: https://api.bintray.com/conan/manromen/rgpaul
  CONAN_REPOSITORY_NAME: rgpaul
  CONAN_PACKAGE_NAME: zlib
  CONAN_USER: rgpaul
  CONAN_CHANNEL: stable

on: 
  push:
    branches:
      - master

jobs:
  
  Device-Release:
    runs-on: macOS-latest
    env:
      GITHUB_OS_NAME: macos
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-ios.sh armv8 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  Device-Debug:
    runs-on: macOS-latest
    env:
      GITHUB_OS_NAME: macos
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-ios.sh armv8 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  Simulator:
    runs-on: macOS-latest
    env:
      GITHUB_OS_NAME: macos
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-ios.sh x86_64 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
