name: macOS

env:
  BINTRAY_USER: manromen
  CONAN_REPOSITORY: https://api.bintray.com/conan/manromen/rgpaul
  CONAN_REPOSITORY_NAME: rgpaul
  CONAN_USER: rgpaul
  CONAN_CHANNEL: stable

on:
  create:
    ref_type: tag

jobs:
  
  x86_64-Release:
    runs-on: macOS-latest
    env:
      GITHUB_OS_NAME: macos
      DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(echo ${GITHUB_REF:10})
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-macos.sh x86_64 Release
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh

  x86_64-Debug:
    runs-on: macOS-latest
    env:
      GITHUB_OS_NAME: macos
      DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(echo ${GITHUB_REF:10})
    - name: install and setup conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-macos.sh x86_64 Debug
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
