name: Windows

env:
  BINTRAY_USER: manromen
  CONAN_REPOSITORY: https://api.bintray.com/conan/manromen/rgpaul
  CONAN_REPOSITORY_NAME: rgpaul
  CONAN_PACKAGE_NAME: zlib
  CONAN_USER: rgpaul
  CONAN_CHANNEL: stable

on: 
  push:
    branches:
      - master

jobs:

  x86_64-Release:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
      shell: bash
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86_64 -BUILD_TYPE Release
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  x86_64-Debug:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
      shell: bash
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86_64 -BUILD_TYPE Debug
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  x86-Release:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
      shell: bash
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86 -BUILD_TYPE Release
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  x86-Debug:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
      shell: bash
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86 -BUILD_TYPE Debug
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  armv7-Release:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
      shell: bash
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH armv7 -BUILD_TYPE Release
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  armv7-Debug:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
      shell: bash
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH armv7 -BUILD_TYPE Debug
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell
